# vars
# {
#   "id": ID_HERE,
#   "type": artist | release | track | podcast | episode
# }

mutation addItemToCollection($id: ID, $type: CollectionItemType) {
  collection {
    addItem(id: $id, type: $type)
  }
}
